blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/<int:pk>/update', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete', BlogDeleteView.as_view(), name='blog_delete')

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog/image', blank=True, null=True, verbose_name='Изображение')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    publication = models.BooleanField(default=True, verbose_name='публикация')
    number_views = models.PositiveIntegerField(verbose_name="Количество просмотров",
                                               help_text="Укажите количество просмотров", default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/views.py
from django.urls import reverse_lazy, reverse

from .models import Blog
from django.views.generic import DetailView, ListView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        return Blog.objects.filter(publication=True)


class BlogCreateView(LoginRequiredMixin,CreateView):
    model = Blog
    fields = ("title", "content", "image", )
    success_url = reverse_lazy("blog:blog_list")


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ("title", "content", "image")
    success_url = reverse_lazy("blog:blog_list")

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_views += 1
        self.object.save()
        return self.object


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Lorem ipsum{% endblock %}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    {% include 'catalog/header.html' %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{% block header_title %}Lorem{% endblock %}</h1>
        <p class="lead">{% block header_description %}Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.{% endblock %}</p>
    </div>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    {% include 'catalog/footer.html' %}

    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text text-center">Вы уверенны?</p>
                    <div class="card-body">
                        {% csrf_token %}
                    </div>
                    <div class="d-grid gap-2 col-4 mx-auto">
                        <button type="submit" class="btn btn-danger ">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Отмена</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="text-center my-5">
        <h1 class="display-4">{{ object.title }}</h1>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="article-content">
                <img src="{{ blog.image | media_filter }}" class="img-fluid mb-4" style="height: auto; max-height: 400px; width: 100%; object-fit: cover;">
                <div class="content-text">
                    <p>{{ object.content }}</p>
                </div>
                <div class="text-center mt-4">
                    <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form class="row g-3" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">
                            {% if object %}
                            Редактировать
                            {% else %}
                            Создать
                            {% endif %}
                        </h5>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <div class="card-footer text-end">
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Список статей</h1>
</div>

<div class="container">
    <div class="list-group">
        {% for blog in object_list %}
        <div class="list-group-item d-flex align-items-start mb-3">
            <div class="me-3" style="flex-shrink: 0;">
                <img src="{{ blog.image|media_filter }}" class="img-fluid" style="height: 180px; object-fit: cover;" alt="{{ blog.title }}">
            </div>
            <div>
                <h4 class="my-0 font-weight-normal">{{ blog.title }}</h4>
                <p class="text-muted">{{ blog.content|truncatechars:150 }}</p>
                <p class="text-muted" style="font-size: 0.9em;">Количество просмотров: {{ blog.number_views }}</p>
                <div class="btn-group mt-2" style="opacity: 0.7;">
                    <a class="btn btn-outline-secondary btn-sm" href="{% url 'blog:blog_detail' blog.pk %}" role="button">Перейти</a>
                    <a class="btn btn-outline-secondary btn-sm" href="{% url 'blog:blog_update' blog.pk %}" role="button">Редактировать</a>
                    <a class="btn btn-outline-danger btn-sm" href="{% url 'blog:blog_delete' blog.pk %}" role="button">Удалить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<div class="row text-center mt-4">
    <div class="col-12">
        <a class="btn btn-primary" href="{% url 'blog:blog_create' %}" role="button">Создать новый блог</a>
    </div>
</div>
{% endblock %}

blog/templates/blog/header.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">store</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contact/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog_list' %}">Блог</a>
    </nav>
</div>