blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/<int:pk>/update', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete', BlogDeleteView.as_view(), name='blog_delete')

]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from catalog.apps import CatalogConfig
from catalog.views import (
    ProductListView,
    ProductDetailView,
    ContactTemplateView,
    ProductCreateView,
    ProductDeleteView,
    ProductUpdateView,
)

app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductListView.as_view(), name="product_list"),
    path("contact/", ContactTemplateView.as_view(), name="contact"),
    path("products/<int:pk>/", cache_page(60)(ProductDetailView.as_view()), name="product_detail"),
    path(
        "product_delete/<int:pk>/", ProductDeleteView.as_view(), name="product_delete"
    ),
    path("product_create/", ProductCreateView.as_view(), name="product_create"),
    path(
        "product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from django.contrib.auth.views import LoginView, LogoutView

from users.views import RegisterView

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "register/",
        RegisterView.as_view(template_name="register.html"),
        name="register",
    ),
]

catalog/models.py
from django.db import models

from users.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name="Наименование")
    description = models.TextField(blank=True, verbose_name="Описание")

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name="Наименование")
    description = models.TextField(blank=True, verbose_name="Описание")
    image = models.ImageField(
        upload_to="catalog/products/", blank=True, null=True, verbose_name="Изображение"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="products",
        verbose_name="Категория",
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="Цена за покупку"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата последнего изменения"
    )
    is_published = models.BooleanField(default=False, verbose_name="Опубликован")

    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Владелец",
        related_name="products",
        null=True,
    )

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["name", "category"]
        permissions = [
            ("can_unpublish_product", "Can unpublish product"),
            ("can_delete_any_product", "Can delete any product"),
        ]

    def __str__(self):
        return self.name

catalog/forms.py
from django import forms
from .models import Product, Category
from django.core.exceptions import ValidationError

forbidden_words = [
    "казино",
    "криптовалюта",
    "крипта",
    "биржа",
    "дешево",
    "бесплатно",
    "обман",
    "полиция",
    "радар",
]


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "image", "category", "price"]

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields["name"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите имя"}
        )
        self.fields["description"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите описание"}
        )
        self.fields["image"].widget.attrs.update({"class": "form-control"})
        self.fields["category"].widget.attrs.update({"class": "form-control"})
        self.fields["price"].widget.attrs.update(
            {"class": "form-control", "placeholder": "Введите цену"}
        )

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if any(word in name.lower() for word in forbidden_words):
            raise ValidationError("Название не должно содержать запрещенные слова.")
        return name

    def clean_description(self):
        description = self.cleaned_data.get("description")
        if any(word in description.lower() for word in forbidden_words):
            raise ValidationError("Название не должно содержать запрещенные слова.")
        return description

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price < 0:
            raise ValidationError("Неверная цена")
        return price

    def clean_image(self):
        image = self.cleaned_data.get("image")
        if image:
            if image.size > 5 * 1024 * 1025:
                raise ValidationError("Файл больше 5МБ")
            if not (
                image.name.endswith(".jpg")
                or image.name.endswith(".jpeg")
                or image.name.endswith(".png")
            ):
                raise ValidationError("Файл не допустимого формата")
        return image


class ProductModeratorForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["is_published"]

    def __init__(self, *args, **kwargs):
        super(ProductModeratorForm, self).__init__(*args, **kwargs)
        self.fields["is_published"].widget.attrs.update({"class": "form-check-input"})


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name", "description"]

catalog/views.py
from django.shortcuts import render
from catalog.models import Product
from django.http import HttpResponse
from django.core.exceptions import PermissionDenied
from django.views.generic import (
    ListView,
    DetailView,
    TemplateView,
    CreateView,
    DeleteView,
    UpdateView,
)
from catalog.forms import ProductForm, ProductModeratorForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from catalog.services import get_products_from_caches


class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        return get_products_from_caches()


class ContactTemplateView(TemplateView):
    template_name = "catalog/contact.html"

    def post(self, request, *args, **kwargs):
        if self.request.method == "POST":
            name = self.request.POST.get("name")
            phone = self.request.POST.get("phone")
            return HttpResponse(f"{name}, {phone}! success!")
        return render(request, "contact.html")


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = "catalog/product_detail.html"
    context_object_name = "product"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            return self.object
        raise PermissionDenied


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_form.html"
    success_url = reverse_lazy("catalog:product_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "catalog/product_form.html"
    success_url = reverse_lazy("catalog:product_list")

    def form_valid(self, form):
        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm("catalog.can_unpublish_product") or user.has_perm(
            "catalog.can_delete_any_product"
        ):
            return ProductModeratorForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = "catalog/product_delete.html"
    success_url = reverse_lazy("catalog:product_list")

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Lorem ipsum{% endblock %}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    {% include 'catalog/header.html' %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{% block header_title %}Lorem{% endblock %}</h1>
        <p class="lead">{% block header_description %}Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.{% endblock %}</p>
    </div>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    {% include 'catalog/footer.html' %}

    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html' %}

{% block title %}Контакты{% endblock %}

{% block header_title %}12345657{% endblock %}

{% block content %}
<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>USA</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>91-1144442</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Redmond,WA,98052-6399</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-6 col-md">
            <h5 class="mt-3 ms-3">Категории</h5> <!-- Добавлен отступ сверху и слева -->
        </div>
        <div class="col-6 col-md">
            <h5 class="mt-3 ms-3">Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5 class="mt-3 ms-3">О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

catalog/templates/catalog/header.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">store</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contact/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog_list' %}">Блог</a>
        {% if user.is_authenticated %}
            <form method="post" action="{% url 'users:logout' %}" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="p-2 btn btn-outline-primary">Выйти</button>
            </form>
            <span class="me-3">Привет, {{ user.email }}!</span>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

catalog/templates/catalog/home.html
{% extends 'base.html' %}
{% load my_tags %}
{% block title %}Lorem{% endblock %}

{% block header_title %}Lorem ipsum dolor sit amet{% endblock %}

{% block content %}
<div class="row text-center">
    <div class="row text-center d-flex">
    {% for product in products %}
    <div class="col-3 d-flex">
        <div class="card mb-4 box-shadow flex-fill">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
            </div>
            <div class="card-body">
                <img src="{{ product.image | media_filter }}" class="img-fluid" style="height: 200px; object-fit: cover;">
                <h1 class="card-title pricing-card-title">${{ product.price }}</h1>
                <p>{{ product.description|truncatechars:100 }}</p>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    {% for feature in product.features.all %}
                    <li>- {{ feature }}</li>
                    {% endfor %}
                </ul>
                <a class="btn btn-primary" href="{% url 'catalog:products_detail' product.pk %}" role="button">Посмотреть</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</div>
{% endblock %}

catalog/templates/catalog/product_delete.html
{% extends 'catalog/base.html' %}
{% block title %}Удаление товара{% endblock %}
{% block content %}
<h2>Удаление товара</h2>

<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <p>Вы уверены, что хотите удалить товар "{{ product.name }}"?</p>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Удалить</button>
                <a href="{% url 'catalog:product_detail' product.pk %}" class="btn btn-secondary">Отмена</a>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <img src="{{ product.image | media_filter }}" class="img-fluid" alt="{{ product.name }}">
            </div>
            <div class="col-md-8">
                <h5 class="card-title">{{ object.name }}</h5>
                <p class="card-text">{{ object.description }}</p>
                <p class="card-text">Категория: {{ object.category }}</p>
                <p class="card-text">Цена: {{ object.price }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a class="btn btn-warning w-100" href="{% url 'catalog:product_update' product.pk %}">Изменить</a>
                        <a class="btn btn-danger w-100" href="{% url 'catalog:product_delete' product.pk %}">Удалить</a>
                        <a class="btn btn-primary" href="{% url 'catalog:product_list' %}" role="button">Вернуться</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container mt-5">
        <h1 class="mb-4">Форма MyModel</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
                <a class="btn btn-primary" href="{% url 'catalog:product_list' %}">Назад</a>
        </form>
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block title %}Lorem{% endblock %}

{% block header_title %}Lorem ipsum dolor sit amet{% endblock %}

{% block content %}
<div class="row text-center">
    {% for product in object_list %}
    <div class="col-3 d-flex mb-4">
        <div class="card flex-fill h-100">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
            </div>
            <div class="card-body">
                <img src="{{ product.image|media_filter }}" class="img-fluid" style="height: 200px; object-fit: cover;">
                <h1 class="card-title pricing-card-title">${{ product.price }}</h1>
                <p>{{ product.description|truncatechars:100 }}</p>
                <ul class="list-unstyled mt-3 mb-4 text-start">
                    {% for feature in product.features.all %}
                    <li>- {{ feature }}</li>
                    {% endfor %}
                </ul>
                <div class="btn-group" style="margin: 5px;">
                    <a class="btn btn-primary w-100" href="{% url 'catalog:product_detail' product.pk %}" role="button">Посмотреть</a>
                </div>
                <div class="btn-group">
                    {% if perms.catalog.can_unpublish_product and perms.catalog.can_delete_any_product or user == product.owner %}
                    <a class="btn btn-warning w-100" href="{% url 'catalog:product_update' product.pk %}">Изменить</a>
                    <a class="btn btn-danger w-100" href="{% url 'catalog:product_delete' product.pk %}">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <div class="col-12 text-center mt-4">  <!-- Центрируем кнопку создания -->
        <a class="btn btn-primary" href="{% url 'catalog:product_create' %}">Создать</a>
    </div>
</div>

{% endblock %}